### ISSUE TITLE
logging item when collapsing 

### ISSUE THREAD

**Issue by elselapatha** [pratik227/quasar-qhierarchy#1]
in QHierarchy.vue file line No. 125 has console.log statement

**Comment by pratik227** [comment]
My bad. I will remove it in the next release @elselapatha.

**Comment by pratik227** [comment]
I have fixed the issue in version 2.

Github code is not pushed yet. You can use the new version.

Thanks for reporting 👍

**Comment by elselapatha** [comment]
> I have fixed the issue in version 2.
> 
> Github code is not pushed yet. You can use the new version.
> 
> Thanks for reporting 👍
