### ISSUE TITLE
Quasar v2 support

### ISSUE THREAD

**Issue by Karnith** [pratik227/quasar-qhierarchy#10]
Will this project support Quasar v2 with vue v3?

**Comment by pratik227** [comment]
Currently no, It's not migrated yet.

**Comment by pratik227** [comment]
Hi @Karnith,

Just released a new version of qhierarchy(1.0.0-alpha.1 for Quasar v2 with vue v3).

Doc - https://next-quasar-qhierarchy.netlify.app/

Thanks,
Pratik Patel
