### ISSUE TITLE
filter option

### ISSUE THREAD

**Issue by elselapatha** [pratik227/quasar-qhierarchy#2]
Nice to have filter option with custom top slot.
**This is not a bug this is just idea for enhancement **

**Comment by pratik227** [comment]
Yes that's a good idea. Actually I was working on that filter but not able to achieve what I want still WIP. 👍

**Comment by pratik227** [comment]
A new version of QHierarchy is available now.

Demo - https://next-quasar-qhierarchy.netlify.app/example-qhierarchy-filter-demo

If this helped you in any way, you can contribute to the package's long term survival by supporting me
 
https://github.com/sponsors/pratik227

**Comment by pratik227** [comment]
Closing this issue now
