### ISSUE TITLE
Sort Table Not Function

### ISSUE THREAD

**Issue by ricardof18** [pratik227/quasar-qhierarchy#38]
Hello
I try to use sort, but it doesn't work. Clicking the first time works, but the second time it doesn't sort the tree table.
I saw the code and I think I found the problem in the "**sortBy**" function.
Inside the function "**sortBy**" when call function "**sort_recursive**", in the following image shows the function call:
![image](https://user-images.githubusercontent.com/44167524/173768996-edc2c72f-6b5f-4456-8898-943ee84eaafb.png)

I think the problem is that in the else condition is sent "ref(False)", I try to just send false and so sort worked whenever there is click, in the following image shows my solution

![image](https://user-images.githubusercontent.com/44167524/173768939-54783242-565d-428b-98fc-208c212c0425.png)

I hope you can help me with this problem.

**Comment by pratik227** [comment]
Hi @ricardof18,

Thanks for reporting I just published the new version. Can you check on the new version ?

Thanks,
Pratik Patel

**Comment by ricardof18** [comment]
Hello
I've updated and it works.
Another question, is there any way to get the event Sort?
In case i want to sort the server side

**Comment by pratik227** [comment]
I can emit the whole **col** object I think. That will work ?

**Comment by ricardof18** [comment]
Hello
I think along with the column data I need it to be sent in the emit which is the sort order

**Comment by ricardof18** [comment]
Hello
You can to create an function to send columns when click in sort?

**Comment by pratik227** [comment]
@ricardof18 Try new version. Use `sort_column` method

```
<q-hierarchy dense :columns="columns" :data="data" @sort_column="test($event)" :classes="classes" :dark="dark">
      <template v-slot:body="props">
        <td data-th="Name">
          <div v-bind:style="props.setPadding(props.item)"
               :class="props.iconName(props.item)!='done'?'q-pl-lg':''">
            <q-btn @click="props.toggle(props.item)" v-if="props.iconName(props.item)!='done'"
                   :icon="props.iconName(props.item)" flat
                   dense>
            </q-btn>
            <span class="q-ml-sm">{{ props.item.label }}</span>
          </div>
        </td>
        <td class="text-center">{{ props.item.description }}</td>
        <td class="text-left">
          <q-chip color="lime-9" v-if="props.item.note" square size="sm" class="text-white">
            {{ props.item.note }}
          </q-chip>
        </td>
      </template>
    </q-hierarchy>
```

 ```
 methods:{
    test(data){
      console.log(data)
    }
  }
```

**Comment by ricardof18** [comment]
Hello

It´s working. Thanks

Other Question

In your component exists filter search?

**Comment by pratik227** [comment]
@ricardof18 I Tried to implement it but not get the success yet.

**Comment by pratik227** [comment]
Closing this issue
