### ISSUE TITLE
How to add qhierarchy using vue cli + vite 

### ISSUE THREAD

**Issue by meshwara** [pratik227/quasar-qhierarchy#45]
How to use this awesome component using vue cli + vite ?
I have try follow this quide, but no success.
https://www.npmjs.com/package/quasar-ui-qhierarchy
 This error is accoured
`import QHierarchy from"components/QHierarchy";export{default as QHierarchy}from"`

**Comment by pratik227** [comment]
HI @meshwara 

Thanks for reporting. 

Please try the new version.

**1.0.7**

It should work

**Comment by pratik227** [comment]
Closing this issue
