### ISSUE TITLE
When data with "children: null"，qhierarchy can't contract

### ISSUE THREAD

**Issue by Junvary** [pratik227/quasar-qhierarchy#48]
When data with "children: null"，qhierarchy can't contract
data like this:
[
        {
            label: "Node 1",
            description: "Node 1 description",
            note: "Node 1 note",
            children: [
                {
                    children: null,
                    label: "Node 1.1",
                    description: "Node 1.1 description",
                    note: "Node 1.1 note",
                },
                {
                    label: "Node 1.2",
                    description: "Node 1.2 description",
                    note: "Node 1.2 note",
                    children: [
                        {
                            children: null,
                            label: "Node 1.2.1",
                            description: "Node 1.2.1 description",
                            note: "Node 1.2.1 note",
                        },
                        {
                            children: null,
                            label: "Node 1.2.2",
                            description: "Node 1.2.2 description",
                            note: "Node 1.2.2 note",
                        }
                    ],
                }
            ],
    }
 ]

**Comment by pratik227** [comment]
Hi @Junvary,

Thanks for reporting. Please try the latest version. It should work now

**Comment by pratik227** [comment]
Fixed Closing this issue
