### ISSUE TITLE
Default-expand-all not Work

### ISSUE THREAD

**Issue by ricardoferreirafsm** [pratik227/quasar-qhierarchy#51]
Hello
I try to use default-expand-all but it doesn't work.
I was trying to set the variable and after using it inside the defautl-expand-all attribute but it doesn't work
I was already trying to put in real logo but it doesn't work either.
Exists solution for this problem?

**Comment by ricardoferreirafsm** [comment]
I think i know where this problem.
In the file QHierarchy in the function arrayTreeObject, your define vm.first_call with false, therefore it will always be false and does not change.

![image](https://user-images.githubusercontent.com/84498387/189680396-d0b848b4-c068-4a36-b24b-ad9dfb78b7d1.png)

**Comment by ricardoferreirafsm** [comment]
Resolved Problem, without changes.

Insert key in component when there are changes in component is rendered

**Comment by pratik227** [comment]
Ok Great

**Comment by pratik227** [comment]
Hi @ricardoferreirafsm  Can you share like what change you have made to if someone face same issue then it will be easy so solve
