### ISSUE TITLE
Display HTML?

### ISSUE THREAD

**Issue by kev-reth-va** [pratik227/quasar-qhierarchy#55]
I'd like to display HTML hyperlinks and buttons inside QHierarchy but the HTML code appears instead of the rendering. I'd like to do something like this. Is it possible?

![a0ba3e50-d431-48d8-978a-bd8098b8a3d2](https://user-images.githubusercontent.com/101875915/194735445-b30f74f1-fdbf-44f6-ad91-8ca953eb05d0.jpg)

**Comment by pratik227** [comment]
You can use slot and customize the td

Doc - https://next-quasar-qhierarchy.netlify.app/example-qhierarchy-slot-demo

**Comment by pratik227** [comment]
Closing the issue
