### ISSUE TITLE
Possible to expand a row on click

### ISSUE THREAD

**Issue by i-interprete-on-the-fly** [pratik227/quasar-qhierarchy#56]
Hello, thanks for this extension.

I want to expand a row on click with a table so that when a button in a row is clicked, a table to the bottom of this row is "expanded".
Is this possible here?

**Comment by pratik227** [comment]
So you need a emit event on button click ?

**Comment by pratik227** [comment]
Hi @i-interprete-on-the-fly,

Available in latest version.

Demo - https://next-quasar-qhierarchy.netlify.app/example-qhierarchy-row-click-demo

Thanks,
Pratik Patel

**Comment by pratik227** [comment]
Closing this issue
