### ISSUE TITLE
default-expand-all not working on next branch

### ISSUE THREAD

**Issue by absantanna2412** [pratik227/quasar-qhierarchy#63]
No option to expand all by default isnt working on next branch.

You must change the function **arrayTreeObj**

From this:
`vm.first_call = ref(false)`

To this:
`if (this.defaultExpandAll) {
        vm.first_call = ref(true)
      } else {
        vm.first_call = ref(false)
      }`

This avoid the itens to be closed, but for me ist ok

**Comment by pratik227** [comment]
Hi @absantanna2412,

I will check. 

Here I can see it's working - https://next-quasar-qhierarchy.netlify.app/example-qhierarchy-default-expand-all

Thanks,
Pratik Patel

**Comment by pratik227** [comment]
For now closing this issue. Let me know if it does't work I will try to fix it.

**Comment by Orlay86** [comment]
Sorry to bother you again and basically reopening this straight away, but it doesn't work for me on the newest version either.

I tried the changes proposed here and in #51 , but the only result is the hierarchy being expanded and not being able to contract.
Are there any other fixes?
