### ISSUE TITLE
Accessing header row

### ISSUE THREAD

**Issue by Orlay86** [pratik227/quasar-qhierarchy#66]
Is there some way or option to access the header row directly, be it for styling or removing it? 
Since the header slot is not defined and therefore not working of course.
Accessing it with custom CSS selectors etc. also didn't work, at least not for me.

Would appreciate any help.

**Comment by pratik227** [comment]
Hi @Orlay86,

Averrable in latest version. 

Demo - https://next-quasar-qhierarchy.netlify.app/example-qhierarchy-header-slot-demo

Thanks,
Pratik Patel

**Comment by pratik227** [comment]
Closing this issue
