### ISSUE TITLE
Big issue, not compatible with recent quasar app

### ISSUE THREAD

**Issue by renaudham** [pratik227/quasar-qhierarchy#8]
App · Running "qhierarchy" Quasar App Extension...
 App · ⚠️  Extension(qhierarchy): is not compatible with @quasar/app v2.1.9. Required version: ^1.4.3

----------

We need a newer version please, asap

here is what is blocking on node mobule

function extendWithComponent (conf) {
  // make sure boot file is registered
  conf.boot.push('~quasar-app-extension-qhierarchy/src/boot/index.js')

  // make sure boot file transpiles
  conf.build.transpileDependencies.push(/quasar-app-extension-qhierarchy[\\/]src/)
  console.log(` App Extension (qhierarchy) Info: 'Adding qhierarchy boot reference to your quasar.conf.js'`)

}

module.exports = function (api) {
  // extend quasar.conf
  api.registerDescribeApi('QHierarchy', './components/QHierarchy.json')

  api.compatibleWith('quasar', '^1.5.11')
  //api.compatibleWith('@quasar/app', '^1.4.3')

  api.extendQuasarConf(extendWithComponent)
};

**Comment by pratik227** [comment]
Hi,

Thanks for reporting.

try the newer version I have already fix these.

Issue - https://github.com/pratik227/quasar-qhierarchy/issues/6

`  api.compatibleWith('@quasar/app', '^1.4.3 || ^2.0.0')
`

**Comment by renaudham** [comment]
thanks
ok now, great job, working well
just missing new improvement, I hope you will have time
regards

**Comment by pratik227** [comment]
Closing the issue
